config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords' 
  } 

  devise_scope :user do
    get "sign_out", to: redirect("users/sessions#destroy") 
    get '/users', to: redirect("/users/sign_up")
  end

  
  root to: 'entrances#index'

  resources :users,only:[:show] do
    collection do
      patch "swich"
      get "history_input"
      get "history_output"
      get "ranking_all"
    end
  end

  resources :lessons,only: :index do
    member do
      get "inputs"
      get "outputs"
      get "all_inputs_of_base"
      get "all_outputs_of_base"
      get "all_inputs_of_development"
      get "all_outputs_of_development"
      get "all_input_of_lasttask"
      get "all_output_of_lasttask"
    end
    resources :posts, only: [:new,:create]
    resources :input_posts, only: [:new,:create]
  end

  resources :input_posts, only: [:edit,:update,:destroy]

  resources :posts,only: [:show,:update] do
    member do
      get "myshow"
      patch "gooutput"
    end
    collection do
      delete "posts_clear"
    end
    resources :memos,only: :new
  end

  resources :memos,only: [:show,:create,:edit,:update]


  resources :articles do
    collection do
      get 'preview'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
#  ===================================
#  カスタムバリデーション
#  ===================================
VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
# ===================================
# アソシエーション
# ===================================
# extend ActiveHash::Associations::ActiveRecordExtensions
# belongs_to_active_hash :team
has_many :posts,foreign_key: :input_user_id ,primary_key: :id,dependent: :nullify
has_many :posts,foreign_key: :output_user_id ,primary_key: :id,dependent: :nullify
has_many :posts,foreign_key: :next_input_user_id ,primary_key: :id,dependent: :nullify
has_many :posts,foreign_key: :next_output_user_id ,primary_key: :id,dependent: :nullify
has_many :memos ,dependent: :destroy
#  ===================================
#  バリデーション
#  ===================================
validates :name, presence: true, uniqueness: true,length: { maximum: 20 }
validates :slack, presence: true, uniqueness: true,length: { maximum: 50 }
validates :period, presence: true, inclusion: {in: 50..200 }       
validates :style, presence: true, inclusion: {in: 1..2 } 
validates :team_id, presence: true
validates :email, presence: true, uniqueness: true
validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, on: :create
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # # POST /resource/password
  # def create
  #   super
  # end

  # # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected
    def update_resource(resource, params)
      if params[:password].present? && params[:password_confirmation].present?
        resource.update_attributes(params)
      else
        resource.update_without_password(params)
      end
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    current_user.on_off = 0
    current_user.save
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def swich
    if current_user.on_off == 0
      current_user.on_off = 1
      current_user.save
    else
      current_user.on_off = 0
      current_user.save
    end
    redirect_to root_path
  end

  def index
  end


# ===================================
# マイページ
# ===================================
  def show
    @my_input_posts = Post.where(input_or_output: 0).where(input_user_id:current_user.id)
    @my_output_posts = Post.where(input_or_output: 1).where(next_output_user_id:current_user.id)
    @my_clear_posts = Post.where(input_or_output: 2).where(next_output_user_id:current_user.id)
  end

# ===================================
# input履歴表示用
# ===================================
  def history_input
    @first_input_posts = Post.where(input_user_id: current_user.id).where.not(input_or_output:0)
    # 質問から教えますに移行した投稿を格納([おしえます]と[fito]の場合がありえる)
    @second_input_posts = Post.where(next_input_user_id: current_user.id,input_or_output:2)
    # 教えます掲示板からfitOに移行した投稿を格納(fitoの場合しかない)
  end

  # ===================================
# output履歴表示用
# ===================================
  def history_output
    @first_output_posts_from_question = Post.where(output_user_id: current_user.id).where.not(input_or_output:0)
    # 掲示板から教えた場合に移行した投稿を格納
    @second_output_posts_from_mypost = Post.where(next_output_user_id: current_user.id,input_or_output:2)
    # 掲示板から教えた投稿を格納
  end
# ===================================
# ランキング履歴表示用
# ===================================
  def ranking_all
    @q = User.search(params[:q])
    users = @q.result
    @users = users.order(output_times: "DESC") 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/history_input.html.haml
.post_all
  .post_all_inner
    .history_category
      インプット履歴
      .history_inner
        .history_sub_category
          質問投稿から
        - @first_input_posts.each do |post|
          .history_onebox
            = link_to "",myshow_post_path(post.id)
            .history_oneline
              - case post.lesson.base_or_development
                - when 0 then
                  = "基礎"
                - when 1 then
                  = "応用"
                - when 2 then
                  = "最終"
              = "lesson:#{post.lesson.lesson_no}"
              = post.title
            .history_oneline
              - if post.output_user_id? && User.exists?(id: post.output_user_id)
                = "教えてもらった人：[name]#{post.output_user.name}[slack]#{post.output_user.slack}"
              - else
                教えてもらったユーザーは退会しています。
            .history_oneline
              = "教えてもらった日時：#{post.first_update_date}".gsub(/\+0900/,"" )
              -# inputからouput移行した日時
      .history_inner
        .history_sub_category
          掲示板から
        - @second_input_posts.each do |post|
          .history_onebox
            = link_to "",myshow_post_path(post.id)
            .history_oneline
              - case post.lesson.base_or_development
                - when 0 then
                  = "基礎"
                - when 1 then
                  = "応用"
                - when 2 then
                  = "最終"
              = "lesson:#{post.lesson.lesson_no}"
              = post.title
            .history_oneline
              - if post.next_output_user_id? && User.exists?(id: post.next_output_user_id)
                = "教えてもらった人：[name]#{post.next_output_user.name}[slack]#{post.next_output_user.slack}"
              - else
                教えてもらったユーザーは退会しています
            .history_oneline
              = "教えてもらった日時：#{post.updated_at}".gsub(/\+0900/,"" )
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[質問投稿から]・・・自分が質問を投稿し、教えてもらった履歴です。クリックで詳細が確認でます。
          %p
            ○[掲示板から]・・・掲示板から、質問し教えてもらった履歴です。クリックで詳細が確認でます。

 

app/views/users/history_output.html.haml
.post_all
  .post_all_inner
    .history_category
      アウトプット履歴
      .history_inner
        .history_sub_category
          質問投稿・教えます投稿から
        - @second_output_posts_from_mypost.each do |post|
          .history_onebox
            = link_to "",myshow_post_path(post.id)
            .history_oneline
              - case post.lesson.base_or_development
                - when 0 then
                  = "基礎"
                - when 1 then
                  = "応用"
                - when 2 then
                  = "最終"
              = "lesson:#{post.lesson.lesson_no}"
              = post.title
            .history_oneline
              - if post.next_input_user_id? && User.exists?(id: post.next_input_user_id)
                = "教えた人：[name]#{post.next_input_user.name}[slack]#{post.next_input_user.slack}"
              - else
                教えたユーザーは退会しています。
            .history_oneline
              = "教えた日時：#{post.updated_at}".gsub(/\+0900/,"" )
      .history_inner
        .history_sub_category
          掲示板から
        - @first_output_posts_from_question.each do |post|
          .history_onebox
            = link_to "",myshow_post_path(post.id)
            .history_oneline
              - case post.lesson.base_or_development
                - when 0 then
                  = "基礎"
                - when 1 then
                  = "応用"
                - when 2 then
                  = "最終"
              = "lesson:#{post.lesson.lesson_no}"
              = post.title
            .history_oneline
              - if post.input_user_id.present? && User.exists?(id: post.input_user_id)
                = "教えた人：[name]#{post.input_user.name}[slack]#{post.input_user.slack}"
              - else
                教えたユーザーは退会しています。
            .history_oneline
              = "教えた日時：#{post.first_update_date}".gsub(/\+0900/,"" )
              -# inputからouput移行した日時
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[質問投稿・教えます投稿から]・・・自分が質問を投稿し、教えてもらった後、さらに誰かに教えた投稿。「教えます」を投稿し教えた投稿の一覧です。
          %p
            ○[掲示板から]・・・掲示板から、教えた内容の一覧です。

app/views/users/ranking_all.html.haml
.post_all
  .post_all_inner
    .ranking_range
      .search_box
        .search_title
          ランキング範囲を絞る
        = search_form_for @q, url: "/users/ranking_all" do |f| 
          .search_form
            .input_period
              = f.number_field :period_gteq ,min:"50",max:"100"
            %p
              期 〜
            .input_period
              = f.number_field :period_lteq,min:"50",max:"100"
            %p
              期
            .input_style
              スタイル
              = f.select :style_eq, [["短期", 1],["夜間", 2]],:include_blank => '指定なし'
            .input_style
              チーム
              = f.select :team_id_eq, [["A","A" ],["B", "B"],["C", "C"],["D", "D"],["E", "E"],["F","F"],["G", "G"],["H","H"],["I","I"],["J", "J"],["K","K"],["L","L"],["M","M"],["N","N"],["O", "O"],["P","P"],["Q","Q"],["R","R"],["S", "S"],["T","U"],["U","U"],["V", "V"],["W","W"],["X","X"],["Y", "Y"],["Z","Z"]],:include_blank => '指定なし'
            .input_style
              = f.submit "絞る"
      .scroll_mine
        = link_to "自分の位置までスクロール","#mine"
      .ranking_list
        %table
          %th
            %td
              名前
            %td
              アウトプット数
            %td
              期
            %td
              スタイル
            %td
              チーム
            %td
              スラック
          - @users.each_with_index do |user,index|
            - if user.id == current_user.id             
              %tr#mine
                %td.td_ranking
                  = index + 1
                %td.td_name
                  = user.name
                %td
                  = user.output_times
                %td.td_period
                  = user.period
                %td
                  - if user.style == 1
                    短期
                  - else
                    夜間
                %td
                  = user.team_id
                %td.td_name
                  = user.slack
            - else   
              %tr
                %td.td_ranking
                  = index + 1
                %td.td_name
                  = user.name
                %td
                  = user.output_times
                %td.td_period
                  = user.period
                %td
                  - if user.style == 1
                    短期
                  - else
                    夜間
                %td
                  = user.team_id
                %td.td_name
                  = user.slack

  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[ランキングを絞る]・・・期の範囲を指定、スタイル、チームを指定して、条件を絞ることができます。
          %p
            ○[自分の位置までスクロール]・・・ランキングの自分の位置までスクロールします。自分の表示は赤く表示されます。

app/views/users/show.html.haml
.mypage
  .mypage__inner
    .mypage__inner__header
      .mypage__inner__header__topic-id
        fitO_id:
        .mypage__inner__header__topic-id__value
          = "#{current_user.id}"
      .mypage__inner__header__topic
        name:
        .mypage__inner__header__topic__value
          = "#{current_user.name}"
      .mypage__inner__header__topic
        slack:
        .mypage__inner__header__topic__value
          = "#{current_user.slack}"
    .mypage__inner__output-times
      %p
        Output times  : 
      .mypage__inner__output-times__value
        = "#{current_user.output_times}"
    .mypage__inner__tabs
      .mypage__inner__tabs__tab{data: {target: "1"}}
        質問一覧
      .mypage__inner__tabs__tab{data: {target: "2"}}
        教えます一覧
      .mypage__inner__tabs__tab{data: {target: "3"}}
        fitO
    .history_btns
      .history_btn
        = link_to "input履歴" ,history_input_users_path
      .history_btn
        = link_to "Output履歴",history_output_users_path
.post_all
  .post_all_inner.none{data: {target: "1"}}
    - @my_input_posts.each do |post|
      .one_post
        .show_link
          = link_to "",myshow_post_path(post.id)
        .one_post__title
          - case post.lesson.base_or_development
            - when 0 then
              = "基礎"
            - when 1 then
              = "応用"
            - when 2 then
              = "最終"
          = "lesson:#{post.lesson.lesson_no}"
          = post.lesson.title
        .one_post__title
          = post.title
          = "[id:#{post.id}]"
        .one_post__content
          = toc(post.content) 
          = markdown(post.content)

  .post_all_inner.none{data: {target: "2"}}
    - @my_output_posts.each do |post|
      .one_post
        .show_link
          = link_to "",myshow_post_path(post.id)
        .one_post__title
          - case post.lesson.base_or_development
            - when 0 then
              = "基礎"
            - when 1 then
              = "応用"
            - when 2 then
              = "最終"
          = "lesson:#{post.lesson.lesson_no}"
          = post.lesson.title
        .one_post__title
          = post.title
          = "[id:#{post.id}]"
        .one_post__content
          = toc(post.content) 
          = markdown(post.content)

  .post_all_inner.none{data: {target: "3"}}
    - @my_clear_posts.each do |post|
      .one_post
        .show_link
          = link_to "",myshow_post_path(post.id)
        .one_post__title
          - case post.lesson.base_or_development
            - when 0 then
              = "基礎"
            - when 1 then
              = "応用"
            - when 2 then
              = "最終"
          = "lesson:#{post.lesson.lesson_no}"
          = post.lesson.title
          = "[id:#{post.id}]"
        .one_post__title
          = post.title
        .one_post__content
          = toc(post.content) 
          = markdown(post.content)

  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[input履歴]・・・インプットした履歴が確認できます。
          %p
            ○[output履歴]・・・アウトプットした履歴が確認できます。
          %p
            ○[output times]・・・アウトプットした回数が表示されます。
          %p
            ○[質問一覧]・・・ 現在投稿中の質問が確認できます。また、教えてもらった場合は、詳細表示から、教えてもらった人のidを入力してください。（そうすることで、教えてもらった人のアウトプット回数が計上されます。）
          %p
            ○[教えます一覧]・・・現在投稿中の「教えます」一覧が確認できます。
          %p
            ○[fitO]・・・アウトプット済の投稿が確認できます。