config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords' 
  } 

  devise_scope :user do
    get "sign_out", to: redirect("users/sessions#destroy") 
    get '/users', to: redirect("/users/sign_up")
  end

  
  root to: 'entrances#index'

  resources :users,only:[:show] do
    collection do
      patch "swich"
      get "history_input"
      get "history_output"
      get "ranking_all"
    end
  end

  resources :lessons,only: :index do
    member do
      get "inputs"
      get "outputs"
      get "all_inputs_of_base"
      get "all_outputs_of_base"
      get "all_inputs_of_development"
      get "all_outputs_of_development"
      get "all_input_of_lasttask"
      get "all_output_of_lasttask"
    end
    resources :posts, only: [:new,:create]
    resources :input_posts, only: [:new,:create]
  end

  resources :input_posts, only: [:edit,:update,:destroy]

  resources :posts,only: [:show,:update] do
    member do
      get "myshow"
      patch "gooutput"
    end
    collection do
      delete "posts_clear"
    end
    resources :memos,only: :new
  end

  resources :memos,only: [:show,:create,:edit,:update]


  resources :articles do
    collection do
      get 'preview'
    end
  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :posts

  validates :active, presence: true, inclusion: {in: 0..1 } 
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    # それぞれのレッスンに対するカリキュラムを格納
    @base1 = Lesson.where(base_or_development:0,lesson_no:1,active:1).order(sub_number: "ASC")
    @base2 = Lesson.where(base_or_development:0,lesson_no:2,active:1).order(sub_number: "ASC")
    @base3 = Lesson.where(base_or_development:0,lesson_no:3,active:1).order(sub_number: "ASC")
    @base4 = Lesson.where(base_or_development:0,lesson_no:4,active:1).order(sub_number: "ASC")
    @base5 = Lesson.where(base_or_development:0,lesson_no:5,active:1).order(sub_number: "ASC")
    @base6 = Lesson.where(base_or_development:0,lesson_no:6,active:1).order(sub_number: "ASC")
    @base7 = Lesson.where(base_or_development:0,lesson_no:7,active:1).order(sub_number: "ASC")
    @base8 = Lesson.where(base_or_development:0,lesson_no:8,active:1).order(sub_number: "ASC")
    @base9 = Lesson.where(base_or_development:0,lesson_no:9,active:1).order(sub_number: "ASC")
    @bases = [@base1,@base2,@base3,@base4,@base5,@base6,@base7,@base8,@base9]

    @development1 = Lesson.where(base_or_development:1,lesson_no:1,active:1).order(sub_number: "ASC")
    @development2 = Lesson.where(base_or_development:1,lesson_no:2,active:1).order(sub_number: "ASC")
    @development3 = Lesson.where(base_or_development:1,lesson_no:3,active:1).order(sub_number: "ASC")
    @development4 = Lesson.where(base_or_development:1,lesson_no:4,active:1).order(sub_number: "ASC")
    @development5 = Lesson.where(base_or_development:1,lesson_no:5,active:1).order(sub_number: "ASC")
    @development6 = Lesson.where(base_or_development:1,lesson_no:6,active:1).order(sub_number: "ASC")
    @development7 = Lesson.where(base_or_development:1,lesson_no:7,active:1).order(sub_number: "ASC")
    @development8 = Lesson.where(base_or_development:1,lesson_no:8,active:1).order(sub_number: "ASC")
    @development9 = Lesson.where(base_or_development:1,lesson_no:9,active:1).order(sub_number: "ASC")
    @development10 = Lesson.where(base_or_development:1,lesson_no:10,active:1).order(sub_number: "ASC")
    @development11 = Lesson.where(base_or_development:1,lesson_no:11,active:1).order(sub_number: "ASC")
    @development12 = Lesson.where(base_or_development:1,lesson_no:12,active:1).order(sub_number: "ASC")
    @development13 = Lesson.where(base_or_development:1,lesson_no:13,active:1).order(sub_number: "ASC")
    @development14 = Lesson.where(base_or_development:1,lesson_no:14,active:1).order(sub_number: "ASC")

    @developments = [@development1,@development2,@development3,@development4,@development5,
                     @development6,@development7,@development8,@development9,@development10,
                     @development11,@development12, @development13,@development14]

    @last_task = Lesson.where(base_or_development:2,lesson_no:1,active:1).order(sub_number: "ASC")
  end

  
  def inputs
    @input_posts = Post.where(lesson_id: params[:id]).where(input_or_output: 0)
    @lesson = Lesson.find(params[:id])
      case @lesson.base_or_development
        when 0 then
          @category = "基礎"
        when 1 then
          @category = "応用"
        when 2 then
          @category = "最終"
        end
  end

  def outputs
    @output_posts = Post.where(lesson_id: params[:id]).where(input_or_output: 1)
    @lesson = Lesson.find(params[:id])
      case @lesson.base_or_development
      when 0 then
        @category = "基礎"
      when 1 then
        @category = "応用"
      when 2 then
        @category = "最終"
      end
  end

  def all_inputs_of_base
    @all_posts = []
    target_lessons = Lesson.where(lesson_no: params[:id]).where(base_or_development:0)
    target_lessons.each do |target_lesson|
      @all_posts << target_lesson.posts.where(input_or_output:0)
    end 
    @all_posts = @all_posts.delete_if(&:empty?).flatten
    render "lessons/all_inputs"
  end

  def all_inputs_of_development
    @all_posts =[]
    target_lessons = Lesson.where(lesson_no: params[:id]).where(base_or_development:1)
    target_lessons.each do |target_lesson|
      @all_posts << target_lesson.posts.where(input_or_output:0)
    end 
    @all_posts = @all_posts.delete_if(&:empty?).flatten
    render "lessons/all_inputs"
  end

  def all_input_of_lasttask
    @all_posts =[]
    target_lessons = Lesson.where(lesson_no: params[:id]).where(base_or_development:2)
    target_lessons.each do |target_lesson|
      @all_posts << target_lesson.posts.where(input_or_output:0)
    end 
    @all_posts = @all_posts.delete_if(&:empty?).flatten
    render "lessons/all_inputs"
  end

  def all_outputs_of_base
    @all_posts =[]
    target_lessons = Lesson.where(lesson_no: params[:id]).where(base_or_development:0)
    target_lessons.each do |target_lesson|
      @all_posts << target_lesson.posts.where(input_or_output:1)
    end 
    @all_posts = @all_posts.delete_if(&:empty?).flatten
    render "lessons/all_outputs"
  end

  def all_outputs_of_development
    @all_posts =[]
    target_lessons = Lesson.where(lesson_no: params[:id]).where(base_or_development:1)
    target_lessons.each do |target_lesson|
      @all_posts << target_lesson.posts.where(input_or_output:1)
    end 
    @all_posts = @all_posts.delete_if(&:empty?).flatten
    render "lessons/all_outputs"
  end



  def all_output_of_lasttask
    @all_posts =[]
    target_lessons = Lesson.where(lesson_no: params[:id]).where(base_or_development:2)
    target_lessons.each do |target_lesson|
      @all_posts << target_lesson.posts.where(input_or_output:1)
    end 
    @all_posts = @all_posts.delete_if(&:empty?).flatten
    render "lessons/all_outputs"
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/all_inputs.html.haml
-# ===================================
-# 全てを表示(インプット)
-# ===================================
.post_all
  .post_all_inner
    - @all_posts.each do |post|
      .one_post
        .show_link
          = link_to "",post_path(post.id)
        .one_post__title
          = post.title
          = "[id:#{post.id}]"
        .one_post__content
          = toc(post.content) 
          = markdown(post.content)
        - if post.input_user_id == current_user.id  # 自分の質問投稿の場合
          .your_display
            これはあなたの投稿です。
        - if post.input_user_id? && User.exists?(id: post.input_user_id)
          - if post.input_user.on_off == 1
            .on_off_dispry
              出席中 
        - else
          .on_off_dispry
            退会済
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[詳細を確認する]・・・一覧から、クリックするとその投稿の詳細が確認できます。
          %p
            ○[掲示板から教える]・・・自分が教えたい内容と同様の投稿があれば、スラックで投稿者に連絡をとり、アウトプットしてください。
          %p
            ○[「教えます」を投稿する]・・・自分が教えたい内容と同様の投稿がなければ、右下の「教えますを投稿する」ボタンをクリックしてください。
          %p
            ○[表示について]・・・ 自分の投稿及び投稿者が出席中の場合は、その旨が一覧に表示されます。

app/views/lessons/all_inputs_of_base.html.haml
-# ===================================
-# 質問全て（基礎）
-# ===================================
.post_all
  .post_all_inner
    koko
    - @all_input_posts_of_lesson_base.each do |post|
      .one_post
        = link_to "",post_path(post[0].id)
        .one_post__title
          = post[0].title
          = "[id:#{post[0].id}]"
        .one_post__content
          = toc(post[0].content) 
          = markdown(post[0].content)
        - if post[0].input_user_id == current_user.id  # 自分の質問投稿の場合
          .your_display
            これはあなたの投稿です。
        - if post[0].input_user_id? && User.exists?(id: post[0].input_user_id)
          - if post[0].input_user.on_off == 1
            .on_off_dispry
              出席中 
        - else
          .on_off_dispry
            退会済
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[詳細を確認する]・・・一覧から、クリックするとその投稿の詳細が確認できます。
          %p
            ○[掲示板から教える]・・・自分が教えたい内容と同様の投稿があれば、スラックで投稿者に連絡をとり、アウトプットしてください。
          %p
            ○[「教えます」を投稿する]・・・自分が教えたい内容と同様の投稿がなければ、右下の「教えますを投稿する」ボタンをクリックしてください。
          %p
            ○[表示について]・・・ 自分の投稿及び投稿者が出席中の場合は、その旨が一覧に表示されます。

app/views/lessons/all_outputs.html.haml
-# ===================================
-# 全てを表示(アウトプット)
-# ===================================
.post_all
  .post_all_inner
    - @all_posts.each do |post|
      .one_post
        .show_link
          = link_to "",post_path(post.id)
        .one_post__title
          = post.title
          = "[id:#{post.id}]"
        .one_post__content
          - if post.start_input_or_output == 0
            .attention
              この質問は解決しました！同じ質問がある方はお教えします！
          = toc(post.content) 
          = markdown(post.content)
        - if post.next_output_user_id == current_user.id
          .your_display
            これはあなたの投稿です。
        - if post.next_output_user_id? && User.exists?(id: post.next_output_user_id)
          - if post.next_output_user.on_off == 1
            .on_off_dispry
              出席中 
        - else
          .on_off_dispry
            退会済
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[詳細を確認する]・・・一覧から、クリックするとその投稿の詳細が確認できます。
          %p
            ○[掲示板から教える]・・・自分が教えたい内容と同様の投稿があれば、スラックで投稿者に連絡をとり、アウトプットしてください。
          %p
            ○[「教えます」を投稿する]・・・自分が教えたい内容と同様の投稿がなければ、右下の「教えますを投稿する」ボタンをクリックしてください。
          %p
            ○[表示について]・・・ 自分の投稿及び投稿者が出席中の場合は、その旨が一覧に表示されます。

app/views/lessons/index.html.haml
.lesson_box
  .TABS
    .first_tab#outputer_first_tab
      教える
    .first_tab#intputer_first_tab
      質問する
  .TABS.second_tabs#outputer_second_tabs.none
    .second_tab{data: {target: "1"}}
      基礎
    .second_tab{data: {target: "2"}}
      応用
    .second_tab{data: {target: "3"}}
      最終課題
  .TABS.second_tabs#inputer_second_tabs.none
    .second_tab{data: {target: "4"}}
      基礎
    .second_tab{data: {target: "5"}}
      応用
    .second_tab{data: {target: "6"}}
      最終課題
  -# ===================================
  -# lessonタブを作成
  -# ===================================
  .TABS.number_tabs.none{data: {target: "1"}}
    - i = 1
    - n = 101
    - while i < 10 do
      .third_tab
        = link_to "#{i}","#lesson#{n}"
      - i += 1
      - n += 1

  .TABS.number_tabs.none{data: {target: "2"}}
    - i = 1
    - n = 201
    - while i < 15 do
      .third_tab
        = link_to "#{i}","#lesson#{n}"
      - i += 1
      - n += 1

  .TABS.number_tabs.none{data: {target: "4"}}
    - i = 1
    - n = 401
    - while i < 10 do
      .third_tab
        = link_to "#{i}","#lesson#{n}"
      - i += 1
      - n += 1

  .TABS.number_tabs.none{data: {target: "5"}}
    - i = 1
    - n = 501
    - while i < 15 do
      .third_tab
        = link_to "#{i}","#lesson#{n}"
      - i += 1
      - n += 1
    -# ===================================
    -# レッスン一覧を6通り作成
    -# ===================================
    -# ===================================
    -# 質問一覧
    -# ===================================  
  .lists.none{data: {target: "1"}}
    - i = 1
    - n = 101
    - @bases.each do |base|
      - total = 0
      .lesson_lists{id: "lesson#{n}"}
        .lesson_no
          = "lesson #{i}"
        - base.each do |lesson|
          .lesson_lists__one
            .lesson_lists__one__title
              = link_to"#{lesson.title}",inputs_lesson_path(lesson.id)
            .lesson_lists__one__number
              = "投稿数：#{lesson.posts.where(input_or_output:0).length}"
              - total += lesson.posts.where(input_or_output:0).length
        .lesson_lists__one
          .lesson_lists__one__title
            = link_to"全て見る(lesson:#{i})",all_inputs_of_base_lesson_path(i)
          .lesson_lists__one__number
            = "投稿数：#{total}"
      - i += 1
      - n += 1

  .lists.none{data: {target: "2"}}
    - i = 1
    - n = 201
    - @developments.each do |development|
      - total = 0
      .lesson_lists{id: "lesson#{n}"}
        .lesson_no
          = "lesson #{i}"
        - development.each do |lesson|
          .lesson_lists__one
            .lesson_lists__one__title
              = link_to"#{lesson.title}",inputs_lesson_path(lesson.id)
            .lesson_lists__one__number
              = "投稿数：#{lesson.posts.where(input_or_output:0).length}"
              - total += lesson.posts.where(input_or_output:0).length
        .lesson_lists__one
          .lesson_lists__one__title
            = link_to"全て見る(lesson:#{i})",all_inputs_of_development_lesson_path(i)
          .lesson_lists__one__number
            = "投稿数：#{total}"
      - i += 1
      - n += 1

  .lists.none{data: {target: "3"}}
    .lesson_lists
      .lesson_no
        最終課題
      - total = 0
      - @last_task.each do |lesson|
        .lesson_lists__one
          .lesson_lists__one__title
            = link_to"#{lesson.title}",inputs_lesson_path(lesson.id)
          .lesson_lists__one__number
            = "投稿数：#{lesson.posts.where(input_or_output:0).length}"
            - total += lesson.posts.where(input_or_output:0).length
      .lesson_lists__one
        .lesson_lists__one__title
          = link_to"全て見る(lesson:#{i})",all_input_of_lasttask_lesson_path(1)
        .lesson_lists__one__number
          = "投稿数：#{total}"
    -# ===================================
    -# 教えます一覧
    -# ===================================  
      
  .lists.none{data: {target: "4"}}
    - i = 1
    - n = 401
    - @bases.each do |base|
      - total = 0
      .lesson_lists{id: "lesson#{n}"}
        .lesson_no
          = "lesson #{i}"
        - base.each do |lesson|
          .lesson_lists__one
            .lesson_lists__one__title
              = link_to"#{lesson.title}",outputs_lesson_path(lesson.id)
            .lesson_lists__one__number
              = "投稿数：#{lesson.posts.where(input_or_output:1).length}"
              - total += lesson.posts.where(input_or_output:1).length
        .lesson_lists__one
          .lesson_lists__one__title
            = link_to"全て見る",all_outputs_of_base_lesson_path(i)
          .lesson_lists__one__number
            = "投稿数：#{total}"
      - i += 1
      - n += 1

  .lists.none{data: {target: "5"}}
    - i = 1
    - n = 501
    - @developments.each do |development|
      - total = 0
      .lesson_lists{id: "lesson#{n}"}
        .lesson_no
          = "lesson #{i}"
        - development.each do |lesson|
          .lesson_lists__one
            .lesson_lists__one__title
              = link_to"#{lesson.title}",outputs_lesson_path(lesson.id)
            .lesson_lists__one__number
              = "投稿数：#{lesson.posts.where(input_or_output:1).length}"
              - total += lesson.posts.where(input_or_output:1).length
        .lesson_lists__one
          .lesson_lists__one__title
            = link_to"全て見る",all_outputs_of_development_lesson_path(i)
          .lesson_lists__one__number
            = "投稿数：#{total}"
      - i += 1
      - n += 1

  .lists.none{data: {target: "6"}}
    .lesson_lists{id: "lesson#{i}"}
      .lesson_no
        最終課題
      - total = 0
      - @last_task.each do |lesson|
        .lesson_lists__one
          .lesson_lists__one__title
            = link_to"#{lesson.title}",outputs_lesson_path(lesson.id)
          .lesson_lists__one__number
            = "投稿数：#{lesson.posts.where(input_or_output:1).length}"
            - total += lesson.posts.where(input_or_output:1).length
      .lesson_lists__one
        .lesson_lists__one__title
          = link_to"全て見る",all_output_of_lasttask_lesson_path(1)
        .lesson_lists__one__number
          = "投稿数：#{total}"

  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[教える場合]・・・タブで教えるをクリックし、区分、lessonを選択し、「質問」一覧を確認してください。
          %p
            ○[質問する場合]・・・タブで教えるをクリックし、区分、lessonを選択し、「教えます」一覧を確認してください。
          %p
            レッスン番号タブをクリックすると当該レッスンの位置までスクロールします。  

app/views/lessons/inputs.html.haml
-# ===================================
-# 質問一覧
-# ===================================
.post_all
  .post_all_inner
    .categoly
      =  "質問一覧  ＞  #{@category}  ＞  LESSON.#{@lesson.lesson_no} ＞ #{@lesson.title}"
    - @input_posts.each do |post|
      .one_post
        .show_link
          = link_to "",post_path(post.id)
        .one_post__title
          = post.title
          = "[id:#{post.id}]"
        .one_post__content
          = toc(post.content) 
          = markdown(post.content)
        - if post.input_user_id == current_user.id  # 自分の質問投稿の場合
          .your_display
            これはあなたの投稿です。
        - if post.input_user_id? && User.exists?(id: post.input_user_id)
          - if post.input_user.on_off == 1
            .on_off_dispry
              出席中 
        - else
          .on_off_dispry
            退会済

    .create_btn
      = link_to "「教えます」を投稿する",new_lesson_post_path(@lesson.id)
      
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[詳細を確認する]・・・一覧から、クリックするとその投稿の詳細が確認できます。
          %p
            ○[掲示板から教える]・・・自分が教えたい内容と同様の投稿があれば、スラックで投稿者に連絡をとり、アウトプットしてください。
          %p
            ○[「教えます」を投稿する]・・・自分が教えたい内容と同様の投稿がなければ、右下の「教えますを投稿する」ボタンをクリックしてください。
          %p
            ○[表示について]・・・ 自分の投稿及び投稿者が出席中の場合は、その旨が一覧に表示されます。

app/views/lessons/outputs.html.haml
-# ===================================
-# 教えます一覧
-# ===================================
.post_all
  .post_all_inner
    .categoly
      =  "教えます一覧  ＞  #{@category}  ＞  LESSON.#{@lesson.lesson_no} ＞ #{@lesson.title}"
    - @output_posts.each do |post|
      .one_post
        .show_link
          = link_to "",post_path(post.id)
        .one_post__title
          = post.title
          = "[id:#{post.id}]"
        .one_post__content
          - if post.start_input_or_output == 0
            .attention
              この質問は解決しました！同じ質問がある方はお教えします！
          = toc(post.content) 
          = markdown(post.content)
        - if post.next_output_user_id == current_user.id  # 自分の教えます投稿の場合
          .your_display
            これはあなたの投稿です。
        - if post.next_output_user_id? && User.exists?(id: post.next_output_user_id)
          - if post.next_output_user.on_off == 1
            .on_off_dispry
              出席中
        - else
          .on_off_dispry
            退会済


    .create_btn
      = link_to "「質問」を投稿する",new_lesson_input_post_path(@lesson.id)

  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[詳細を確認する]・・・一覧から、クリックするとその投稿の詳細が確認できます。
          %p
            ○[掲示板から質問する]・・・自分が質問内容と同様の投稿があれば、スラックで投稿者に連絡をとり、質問してください。教えてももらった後、詳細画面から教えてもらった人のidを入力してください。（この作業をすることで、教えてもらった人のアウトプット回数が計上されます。）
          %p
            ○[「質問」を投稿する]・・・自分が知りたい内容と同様の投稿がなければ、右下の「質問を投稿する」ボタンをクリックしてください。
          %p
            ○[表示について]・・・ 自分の投稿及び投稿者が出席中の場合は、その旨が一覧に表示されます。  