config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords' 
  } 

  devise_scope :user do
    get "sign_out", to: redirect("users/sessions#destroy") 
    get '/users', to: redirect("/users/sign_up")
  end

  
  root to: 'entrances#index'

  resources :users,only:[:show] do
    collection do
      patch "swich"
      get "history_input"
      get "history_output"
      get "ranking_all"
    end
  end

  resources :lessons,only: :index do
    member do
      get "inputs"
      get "outputs"
      get "all_inputs_of_base"
      get "all_outputs_of_base"
      get "all_inputs_of_development"
      get "all_outputs_of_development"
      get "all_input_of_lasttask"
      get "all_output_of_lasttask"
    end
    resources :posts, only: [:new,:create]
    resources :input_posts, only: [:new,:create]
  end

  resources :input_posts, only: [:edit,:update,:destroy]

  resources :posts,only: [:show,:update] do
    member do
      get "myshow"
      patch "gooutput"
    end
    collection do
      delete "posts_clear"
    end
    resources :memos,only: :new
  end

  resources :memos,only: [:show,:create,:edit,:update]


  resources :articles do
    collection do
      get 'preview'
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :lesson

  belongs_to :input_user, class_name: "User" , optional: true,foreign_key: "input_user_id"
  belongs_to :output_user, class_name: "User", optional: true,foreign_key: "output_user_id"
  belongs_to :next_input_user, class_name: "User", optional: true,foreign_key: "next_input_user_id"
  belongs_to :next_output_user, class_name: "User", optional: true,foreign_key: "next_output_user_id"
  has_many :memos,dependent: :destroy
  

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# ===================================
# おしえますnew
# ===================================
  def new
    @post = Post.new
  end
# ===================================
# おしえますcreate
# ===================================
  def create
    post = Post.new(output_post_params)
    if post.save
      redirect_to root_path
      flash[:notice] = "「教えたいこと」を投稿しました"
    else 
      flash[:alert] = "タイトルと内容どちらも入力してください"
      redirect_to new_lesson_post_path(params[:lesson_id])
    end
  end
# ===================================
# アップデート(教えますから、クリアへ)
# ===================================
  def update
    if Post.find(params[:id]).next_output_user_id? && User.exists?(id: Post.find(params[:id]).next_output_user_id)
      check_outputer_id = Post.find(params[:id]).next_output_user_id    # 投稿者のidを変数に格納
      if params[:post][:outputer_id].to_i == check_outputer_id    # 投稿者のidと入力のidが正しいかチェック
        Post.find(params[:id]).update(input_or_output: 2,next_input_user_id: current_user.id)   # 投稿をクリアに更新,2次質問者に自分を格納
        output_user = User.find(check_outputer_id)  # 投稿者を変数に格納
        output_user.output_times += 1 # 投稿者のアウトプット回数を計上する
        output_user.save
        flash[:notice] = "この投稿はクリアされました"
        redirect_to root_path
      else
        flash[:alert] = "idがまちがってます"
        redirect_to post_path(params[:id])
      end
    else
      flash[:alert] = "ユーザーが退会しました"
      redirect_to root_path
    end
  end


# ===================================
# 投稿詳細表示用
# ===================================
  def show
    @post = Post.find_by(id:params[:id])
      if  @post.input_or_output == 0
        if @post.input_user_id? && User.exists?(id: @post.input_user_id)
            @slack = @post.input_user.slack
        else
          @slack = "ユーザーは退会しています"
        end 
      else  
        if @post.next_output_user_id? && User.exists?(id: @post.next_output_user_id)
            @slack = @post.next_output_user.slack
        else
            @slack = "ユーザーは退会しています"
        end
      end
  end

# ===================================
# マイページからの詳細表示用
# ===================================
def myshow
  @post = Post.find(params[:id])
    if current_user == @post.input_user || current_user == @post.output_user ||current_user == @post.next_input_user||current_user == @post.next_output_user
      # 自分に関係ない投稿に直接悪説した場合弾く
    else
      flash[:alert] = "不正なアクセスです"
      redirect_to root_path
    end
end

# ===================================
# 質問から教えますへ更新用
# ===================================
def gooutput
  @post = Post.find(params[:id])
  if current_user.id == params[:post][:outputer_id].to_i #自分のidは弾く
    flash[:alert] = "それは自分のidです"
    redirect_to myshow_post_path(params[:id]) 
    return
  else
    if User.find_by(id: params[:post][:outputer_id]) == nil#存在しないidは弾く
      flash[:alert] = "そのユーザーは存在しません"
      redirect_to myshow_post_path(params[:id])
      return
    else
      @post.update(input_or_output: 1,output_user_id: params[:post][:outputer_id],next_output_user_id:current_user.id)
      # この質問をアウトプットへ移行、output_user_idに教えてもらった人のid,next_output_user_idに自分のidを格納
      @post.update(first_update_date: @post.updated_at)
      user = @post.output_user
      user.output_times += 1
      user.save
      # 教えてくれた人のアウトプット回数を計上
      flash[:notice] = "この投稿は「教えます」一覧に移行しました"
      redirect_to root_path
    end
  end
end

# ===================================
# 紐づかない投稿を削除用
# ===================================
def posts_clear
  if current_user.name == "管理者"
  i = 0
  post_all = Post.all
    post_all.each do |post|
      if User.exists?(id: post.input_user_id) || User.exists?(id: post.output_user_id) || User.exists?(id: post.next_input_user_id) || User.exists?(id: post.next_output_user_id)
      else
        post.destroy
        i += 1
      end
    end
  flash[:alert] = "管理者によって、紐づくユーザーのない投稿は削除されました　削除された件数は#{i}件です"
  redirect_to root_path
  return
  else
    flash[:alert] = "管理者のみに権限があります"
    redirect_to root_path
    return
  end

end

private

  def output_post_params
    params.require(:post).permit(:title, :content, :lesson_id,:start_input_or_output).merge(input_or_output: 1,next_output_user_id: current_user.id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/myshow.html.haml
-# ===================================
-# マイページからの投稿詳細
-# ==================================
.post_form#preview
  .form
    .form__title
      .title_field
        = @post.title
        = "[id:#{@post.id}]"
    .form__content
      .content_field
        = toc(@post.content) 
        = markdown(@post.content)
    .form__btns
      .memo_btn
        - unless @post.memos.exists?(user_id: current_user.id)
          = link_to "メモを作成する", new_post_memo_path(@post.id),method: :get
        - else
          = link_to "メモ見る", memo_path(@post.id),method: :get
    -# ==================================
    -# 質問の場合、名前入力箇所,編集削除可能
    -# ==================================
    - if @post.input_or_output == 0 && @post.input_user_id == current_user.id 
      .thanks_for_outputer
        = form_with model: @post, url: {controller: 'posts', action: 'gooutput'},local: true do |f|
          .form__title
            = f.number_field :outputer_id , placeholder: "教えてもらった人のidを入力してください"
            = f.submit "THANKS"
        .edit_destroy_btns
          .edit_btn
            = link_to "編集", edit_input_post_path(@post.id),method: :get
          .destroy_btn
            = link_to "削除", input_post_path(@post.id), method: :delete
    

    -# ==================================
    -# 教えますに投稿した場合に限り、編集削除可能
    -# ==================================
    - if @post.input_or_output == 1 && @post.next_output_user_id == current_user.id && @post.start_input_or_output == 1
      .edit_destroy_btns
        .edit_btn
          = link_to "編集", edit_input_post_path(@post.id),method: :get
        .destroy_btn
          = link_to "削除", input_post_path(@post.id), method: :delete

  -# ===================================
  -# ヒント
  -# ===================================
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[質問]・・・質問は、編集、削除が可能です。
          %p
            ○[教えます]・・・「教えます」は、自ら「教えます」に投稿したもののみ編集、削除が可能です。
          %p
            ※「質問」から「教えます」に移行したものは、誰かに教えるまで掲示板から消すことはできません。

app/views/posts/new.html.haml
-# ===================================
-# 教えます投稿フォーム
-# ===================================
.post_form#mark_down
  .form
    = form_with model: @post, url: {controller: 'posts', action: 'create' },local: true do |f|
      .form__title
        = f.text_field :title, placeholder: "タイトル（教えたい内容）",class: "title_field"
      .form__content
        = f.text_area :content, placeholder: "マークダウン記法を用いてコードブロックを挿入することができます。画像を投稿する場合はgyazoのURLを貼り付けてください。",class: "content_field"
        = f.hidden_field :lesson_id, value: params[:lesson_id]
        = f.hidden_field :start_input_or_output, value: 1
      .form__btns
        .preview_btn
          プレビュー
        = f.submit
  .hint-box.none
    .cancel
      close
    .hint-inner
      .hint-title
        ●ヘッダー
      .hint-content
        %p
          ○[on]・・・出席したらoffボタンをクリックしてください。(あなたの投稿に「出席中」が明示されます。)
        %p
          ○[マイページ]・・・投稿中の掲示板や、過去の履歴が確認できます。
        %p
          ○[ランキング]・・・アウトプット回数のランキングを見ることができます。
        %p
          ○[エディット]・・・ユーザー情報の変更ができます。
        %p
          ○[ログアウト]・・・ログアウトします。
      .hint-title
        ●コンテンツ
        .hint-content
          %p
            ○[タイトル]・・・タイトルを入力してください。レッスンNo等は、自動付与されるため不要です。
          %p
            ○[内容]・・・「教えたい」内容を記載してください。
          %p
            ○[画像の貼り付け]・・・画像を投稿する場合は、gyazoのurlを貼り付けてください。
          %p
            ○[コードの挿入について]・・・ マークダウン記法を用いて、コードブロックの挿入ができます。
          %p
            ○[プレビュー]・・・マークダウン の確認ができます。投稿前に確認しましょう。

.post_form#preview.hidden
  .form
    .form__title
      .title_field#preview_title
        プレビュー表示中
    .form__content
      .content_field#preview_content
    .form__btns
      #md_btn
        記入する

app/views/posts/show.html.haml
-# ===================================
-# 投稿詳細
-# ==================================
.post_form#preview
  .form
    .form__title
      #title_field
        #title_id
          = "#{@post.title}　[id:#{@post.id}]"
        #copy_title_id_btn
          タイトルと掲示板idをコピーする
        #copyalert_title_id.none
          コピーしました。      
    .form__content
      .content_field
        = toc(@post.content) 
        = markdown(@post.content)
    .form__btns
      .slack_box
        .slack_display
          = "Slack　:　"
        #slack_display_copy
          %p
            = "#{@slack}"
        #copy_btn
          slackをコピーする
        #copyalert.none
          コピーしました。

    -# ==================================
    -# 教えますの場合、名前入力箇所
    -# ==================================

    - if @post.next_output_user_id == current_user.id 
    - else
      - if @post.input_or_output == 1 
        - if @post.next_output_user_id? && User.exists?(id: @post.next_output_user_id)
          .thanks_for_outputer
            = form_with model: @post, url: {controller: 'posts', action: 'update'},local: true do |f|
              .form__title
                = f.number_field :outputer_id , placeholder: "教えてもらった人のidを入力してください"
                = f.submit "THANKS"
        - else
          .thanks_for_outputer
            ユーザーが退会しました。