config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords' 
  } 

  devise_scope :user do
    get "sign_out", to: redirect("users/sessions#destroy") 
    get '/users', to: redirect("/users/sign_up")
  end

  
  root to: 'entrances#index'

  resources :users,only:[:show] do
    collection do
      patch "swich"
      get "history_input"
      get "history_output"
      get "ranking_all"
    end
  end

  resources :lessons,only: :index do
    member do
      get "inputs"
      get "outputs"
      get "all_inputs_of_base"
      get "all_outputs_of_base"
      get "all_inputs_of_development"
      get "all_outputs_of_development"
      get "all_input_of_lasttask"
      get "all_output_of_lasttask"
    end
    resources :posts, only: [:new,:create]
    resources :input_posts, only: [:new,:create]
  end

  resources :input_posts, only: [:edit,:update,:destroy]

  resources :posts,only: [:show,:update] do
    member do
      get "myshow"
      patch "gooutput"
    end
    collection do
      delete "posts_clear"
    end
    resources :memos,only: :new
  end

  resources :memos,only: [:show,:create,:edit,:update]


  resources :articles do
    collection do
      get 'preview'
    end
  end

end

app/views/layouts/_header.html.haml
.header
  .fitO_box
    = link_to "" ,root_path
    .fitO
      fitO
    .fitO_sub
      = "-from input to Output-"
  - if user_signed_in?
    - if current_user.on_off == 0
      .swith.off
        = link_to "OFF", swich_users_path, method: :patch
    - else 
      .swith.on
        = link_to "ON", swich_users_path, method: :patch
    .header_btns
      .header_btn
        = link_to "マイページ",user_path(current_user.id), method: :get
      .header_btn
        = link_to "ランキング",ranking_all_users_path, method: :get
      .header_btn
        = link_to "エディット",edit_user_registration_path
      .header_btn
        = link_to "ログアウト",destroy_user_session_path, method: :delete

  - else
    .header_btns
      .header_btn
        = link_to "ログイン", new_user_session_path
      .header_btn
        = link_to "サインアップ",new_user_registration_path

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FitO2
    = csrf_meta_tags
    = csp_meta_tag
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .wrapper 
      = render 'layouts/notifications'
      = render partial: "layouts/header"
      .main-content
        = yield
      .footer
        .footer_btns
          .footer-btn.back
            %button{:onclick => "history.back()", :type => "button"} << 戻る
          .footer-btn.home
            = link_to "ホームに戻る", root_path
          .footer-btn.home.hint
            ヒント
          .footer-btn.foword
            %button{:onclick => "history.forward()", :type => "button"} 進む>>